### ISSUE TITLE
HW 1 Comments

### ISSUE THREAD

**Issue by siarheiv** [aliakseikazhura/LeverX_AliakseiKazhura_sapui5_homework01#1]
1. Please try to avoid using class names like `flexBoxFirst`. It is better to use names with correct semantic meaning like `flexBoxMenu` or similar: you never know when "first" might become "second" and etc. In this case it won't be necessary to do class renamings in html. Also please try to use chaining for some CSS selectors this might be helpful
2. Refresh icon looks a bit off for me (Chrome) 
![image](https://user-images.githubusercontent.com/18071008/36014503-3d1bae68-0d7b-11e8-8f38-b2689eab2184.png)
3. Please avoid using forms for each and every action, this might be redundant as the modern web is based on AJAX.
4. For the font fallbacks try to use fonts with the same stylings: `'Roboto', Times, serif` in my case render `Times` so looks not so pretty like with `Roboto`. In general this is a question to UI/UX expert on the project, not for the developer.
5. Avoid assigning stylings to the whole elements: in your case you are applying styles to the whole `table` element, so all the tables in your project will have the same styles, which might be a problem when you will start adding new tables with different styles.
6. Avoid using mixture of `px` and `pt` sized fonts in the project. Also that is better to use `px` or `em` now: more reading https://stackoverflow.com/questions/3557260/should-i-use-pt-or-px
7. In EDGE browser right side isn't scrolling.

You don't need to fix it now. Please just take into consideration, otherwise looks good!

**Comment by siarheiv** [comment]
@aliakseikazhura Are there any changes? Can we close this?

**Comment by aliakseikazhura** [comment]
yep, I fixed everything in the new version HW
